### ISSUE TITLE
Fix support for Flow 3.3 LTS

### ISSUE THREAD

**Issue by bwaidelich** [Flowpack/jobqueue-common#41]
With https://github.com/Flowpack/jobqueue-common/tree/1.0.1 we broke support for Flow 3.x apparently due to the introduction of named CLI arguments (#35)

**Comment by bwaidelich** [comment]
I can't reproduce the issue with:
```
flowpack/jobqueue-common:1.0.1
flowpack/jobqueue-doctrine:1.0.0
typo3/flow:3.3.x-dev

php 7.1.25
```

Settings:
```yaml
Flowpack:
  JobQueue:
    Common:
      queues:
        'some-queue':
          className: 'Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue'
          executeIsolated: true
```

Everything seems to work as expected.
